language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon --level=max --no-interaction --no-progress src/ tests/
    - php -derror_reporting=E_ALL ./vendor/bin/phpunit
